import type { Metadata } from 'next'
import { Be_Vietnam_Pro, Noto_Serif } from 'next/font/google'
import './globals.css'
import RootLayoutComp from '@/layouts/RootLayout'

const beVietnamPro = Be_Vietnam_Pro({
  variable: '--font-primary',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

const notoSerif = Noto_Serif({
  variable: '--font-secondary',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Reunification Day',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${beVietnamPro.variable} ${notoSerif.variable} antialiased`}>
        <RootLayoutComp>{children}</RootLayoutComp>
      </body>
    </html>
  )
}
